[bar.default]
position = "bottom"
background_opacity = 0.5
center = [ "launcher", "wallpaper", "workspaces", "tray", "clipboard", "notifications", "network", "bluetooth", "volume" ]
end = [ "media", "brightness", "clock" ]
start = [ "cpu", "temp", "ram", "network_rx", "network_tx" ]
margin_ends = 0
widget_spacing = 10
scale = 1.2

    [bar.default.dead_zone.actions]
    left = "settings-toggle"
    scroll_down = "workspace-switch next"
    scroll_up = "workspace-switch prev"

[osd]
position = "bottom_center"
position_vertical = "bottom_center"

[[shell.session.actions]]
action = "lock"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "5"
variant = "destructive"

[[shell.session.actions]]
action = "command"
command = "systemctl soft-reboot"
countdown_seconds = 0.0
enabled = true
glyph = "reboot"
label = "Soft Reboot"
shortcut = "6"
variant = "default"

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "kitty", "niri" ]

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
anchor = true
display = "none"
scale = 1.2
