# --- Window & UI ---
# slightly transparent
background_opacity 0.9
# paddings
window_padding_width 5
# hide window decorations
hide_window_decorations yes

# --- Operations ---
# no confirmation popup when close
confirm_os_window_close 0

# --- Scrolling ---
# more history
scrollback_lines 10000
# faster mouse wheel scrolling
touch_scroll_multiplier 3.0

# --- Font Settings ---
# font
font_family      MesloLGS Nerd Font
bold_font        MesloLGS Nerd Font Mono Bold
italic_font      MesloLGS Nerd Font Mono Italic
bold_italic_font MesloLGS Nerd Font Mono Bold Italic
# font size
font_size        13.0

# --- Colors (Ported from Termux config) ---
# Background & Primary Text
background=#111
foreground=#fff

# Black / Grey
color0=#444
color8=#888

# Red
color1=#d36
color9=#f58

# Green
color2=#3d7
color10=#5f9

# Yellow
color3=#dd8
color11=#ff8

# Blue
color4=#08d
color12=#2af

# Magenta / Purple
color5=#b6d
color13=#d8f

# Cyan
color6=#4dd
color14=#6ff

# White
color7=#eee
color15=#fff

# dms kitty theme override
include dank-tabs.conf
# include dank-theme.conf
