#!/bin/sh

src_dir="$(dirname "$(realpath "$0")")"
dst_dir="$HOME/.local/share/applications"
src="$src_dir/steam-with-mangohud.desktop"
dst="$dst_dir/steam-with-mangohud.desktop"

mkdir -p $dst_dir
ln -sf $src $dst
ls -l $dst
