# --- Window & UI ---
# slightly transparent
background_opacity 0.9
# paddings
window_padding_width 5
# hide window decorations
hide_window_decorations yes

# --- Operations ---
# no confirmation popup when close
confirm_os_window_close 0

# --- Scrolling ---
# more history
scrollback_lines 10000
# faster mouse wheel scrolling
touch_scroll_multiplier 3.0

# --- Font Settings ---
# font
font_family      MesloLGS Nerd Font
bold_font        MesloLGS Nerd Font Mono Bold
italic_font      MesloLGS Nerd Font Mono Italic
bold_italic_font MesloLGS Nerd Font Mono Bold Italic
# font size
font_size        13.0

# --- Colors (Ported from Alacritty config) ---
# general
background #303030
foreground #eeeeee
# normal
color0 #4e4e4e
color1 #eb4129
color2 #abe047
color3 #f6c744
color4 #47a0f3
color5 #7b5cb0
color6 #64dbed
color7 #e5e9f0
# bright
color8 #a0a0a0
color9 #ec5357
color10 #c0e17d
color11 #f9da6a
color12 #49a4f8
color13 #a47de9
color14 #99faf2
color15 #ffffff
