#!/bin/sh

src_dir="$(dirname "$(realpath "$0")")"
dst_dir="$XDG_CONFIG_HOME/environment.d"
src1="$src_dir/01-xdg-base.conf"
dst1="$dst_dir/01-xdg-base.conf"
src2="$src_dir/10-kde-on-niri.conf"
dst2="$dst_dir/10-kde-on-niri.conf"

mkdir -p $dst_dir
ln -sf $src1 $dst1
ls -l $dst1
ln -sf $src2 $dst2
ls -l $dst2
