#!/bin/sh

src_dir="$(dirname "$(realpath "$0")")"
dst_dir="$XDG_CONFIG_HOME/niri"

# niri config
mkdir -p $dst_dir
src="$src_dir/config.kdl"
dst="$dst_dir/config.kdl"
ln -sf $src $dst
ls -l $dst
src="$src_dir/modules"
dst="$dst_dir/modules"
ln -sfn $src $dst
ls -l $dst

# niri helpers
src="$src_dir/helpers/niri.with-center"
dst="/usr/local/bin/niri.with-center"
sudo ln -sf $src $dst
ls -l $dst
src="$src_dir/helpers/niri.with-center-one"
dst="/usr/local/bin/niri.with-center-one"
sudo ln -sf $src $dst
ls -l $dst
