#!/usr/bin/env bash

src="$XDG_CONFIG_HOME/workspace/hdparm/service/hdd-spindown.service"
dst="/etc/systemd/system/hdd-spindown.service"

sudo ln -sf "$src" "$dst"

sudo systemctl daemon-reload
sudo systemctl enable hdd-spindown.service
