#!/usr/bin/env zsh


# Debug
# - chrome://gpu
# - F12 devtools, 'Media' tab
# - nvtop, when running should see the Nvidia device showing DEC[|||| 30%], means the decode chip is being used
# Reference docs:
# - https://wiki.archlinux.org/title/Chromium
# - https://wiki.archlinux.org/title/Hardware_video_acceleration

# define chrome launch flags
local features=(
    # enable Nvidia GPU
    VaapiOnNvidiaGPUs

    # other features
    MiddleClickAutoscroll
)
local flags=(
    # wallet integration
    --password-store=kwallet6

    # cache to ram location, improve performance
    --disk-cache-dir=/tmp/google-chrome

    # features (zsh syntax)
    --enable-features="${(j:,:)features}"
)

# force Nvidia
export LIBVA_DRIVER_NAME=nvidia

# run
exec /opt/google/chrome/google-chrome-original "${flags[@]}" "$@"

# vim: ft=zsh
