#!/usr/bin/env zsh

#
# Original logics from chromium launcher script
#

# Let the wrapped binary know that it has been run through the wrapper.
export CHROME_WRAPPER="/opt/google/chrome/google-chrome"

# Use system xdg utilities. But first create mimeapps.list if it doesn't
# exist; some systems have bugs in xdg-mime that make it fail without it.
xdg_app_dir="${XDG_DATA_HOME:-$HOME/.local/share/applications}"
mkdir -p "$xdg_app_dir"
[ -f "$xdg_app_dir/mimeapps.list" ] || touch "$xdg_app_dir/mimeapps.list"

export CHROME_VERSION_EXTRA="stable"

# We don't want bug-buddy intercepting our crashes. http://crbug.com/41012584
export GNOME_DISABLE_CRASH_DIALOG=SET_BY_GOOGLE_CHROME

# Sanitize std{in,out,err} because they'll be shared with untrusted child
# processes (http://crbug.com/40079595).
exec < /dev/null
exec > >(exec cat)
exec 2> >(exec cat >&2)

#
#
#

# Debug
# - chrome://gpu
# - F12 devtools, 'Media' tab
# - nvtop, when running should see the Nvidia device showing DEC[|||| 30%], means the decode chip is being used
# Reference docs:
# - https://wiki.archlinux.org/title/Chromium
# - https://wiki.archlinux.org/title/Hardware_video_acceleration

# define chrome launch flags
local features=(
    # enable Nvidia GPU
    VaapiOnNvidiaGPUs

    # other features
    MiddleClickAutoscroll
)
local flags=(
    # wallet integration
    --password-store=kwallet6

    # cache to ram location, improve performance
    --disk-cache-dir=/tmp/google-chrome

    # features (zsh syntax)
    --enable-features="${(j:,:)features}"
)

# force Nvidia
export LIBVA_DRIVER_NAME=nvidia

# run
exec -a "$CHROME_WRAPPER" "/opt/google/chrome/chrome" "${flags[@]}" "$@"

# vim: ft=zsh
