#!/usr/bin/env zsh

#
# Original logics from chromium launcher script
# (refer to /opt/google/chrome/google-chrome-original for the origianl code)
#

export CHROME_WRAPPER="/opt/google/chrome/google-chrome"
export CHROME_VERSION_EXTRA="stable"
export GNOME_DISABLE_CRASH_DIALOG=SET_BY_GOOGLE_CHROME

# Use system xdg utilities. But first create mimeapps.list if it doesn't exist; some systems have bugs in xdg-mime that make it fail without it.
xdg_app_dir="${XDG_DATA_HOME:-$HOME/.local/share/applications}"
mkdir -p "$xdg_app_dir"
[ -f "$xdg_app_dir/mimeapps.list" ] || touch "$xdg_app_dir/mimeapps.list"

# Sanitize std{in,out,err} because they'll be shared with untrusted child processes (http://crbug.com/40079595).
exec < /dev/null
exec > >(exec cat)
exec 2> >(exec cat >&2)

#
# Custom logics starts here
#

export LIBVA_DRIVER_NAME=nvidia

# Debug
# - chrome://gpu
# - F12 devtools, 'Media' tab
# - nvtop, when running should see the Nvidia device showing DEC[|||| 30%], means the decode chip is being used
# Reference docs:
# - https://wiki.archlinux.org/title/Chromium
# - https://wiki.archlinux.org/title/Hardware_video_acceleration

# define chrome launch flags
local features=(
    # enable Nvidia GPU
    VaapiOnNvidiaGPUs

    # other features
    MiddleClickAutoscroll
)
local flags=(
    # wallet integration
    --password-store=kwallet6

    # cache to ram location, improve performance
    --disk-cache-dir=/tmp/google-chrome

    # features (zsh syntax)
    --enable-features="${(j:,:)features}"
)

# run the real binary but info it about the wrapper name
exec -a "$CHROME_WRAPPER" "/opt/google/chrome/chrome" "${flags[@]}" "$@"

# vim: ft=zsh
