#!/bin/sh


$XDG_CONFIG_HOME/workspace/steam/scs-software/euro-truck-simulator-2/native/global/install "$@"
$XDG_CONFIG_HOME/workspace/steam/scs-software/euro-truck-simulator-2/native/local/install "$@"
$XDG_CONFIG_HOME/workspace/steam/scs-software/euro-truck-simulator-2/proton/global/install "$@"
$XDG_CONFIG_HOME/workspace/steam/scs-software/euro-truck-simulator-2/proton/local/install "$@"
