#!/bin/sh

cp "$HOME/.config/workspace/tinyproxy/tinyproxy.conf" "$HOME/.config/workspace/tinyproxy/.tinyproxy.conf"
sudo ln -sf "$HOME/.config/workspace/tinyproxy/.tinyproxy.conf" "/etc/tinyproxy/tinyproxy.conf"
sudo ls -l "/etc/tinyproxy/tinyproxy.conf"

