#!/usr/bin/env bash


SOURCE_FILE="$XDG_CONFIG_HOME/workspace/google-chrome/google-chrome-kwallet/google-chrome-kwallet"
TARGET_DIR="/opt/google/chrome"
TARGET_FILE="$TARGET_DIR/google-chrome-kwallet"
sudo ln -sf "$SOURCE_FILE" "$TARGET_FILE"
ls -l "$TARGET_FILE"
