#!/usr/bin/env bash


# Reference docs:
# https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VA-API

# define chrome launch flags
flags=(
    # wallet integration
    --password-store=kwallet6

    --ignore-gpu-blocklist
    --enable-zero-copy
    --enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecoder,VaapiOnNvidiaGPUs,VaapiVideoDecoder


    # wayland display server
    # --ozone-platform=wayland

    #
    # --use-gl=desktop
    # --use-angle=vulkan

    # force intel iGPU render node (129) instead of nvidia (128)
    # --render-node-override=/dev/dri/renderD129
    # --render-node-override=/dev/dri/renderD128

    # feature flags
    # --enable-features=Vulkan,CanvasOopRasterization,WaylandLinuxDrmSyncobj,UseMultiPlaneFormatForHardwareVideo
    # --disable-features=UseChromeOSDirectVideoDecoder

    # workaround 
    # --disable-gpu-driver-bug-workarounds
    # --disable-gpu-vsync
)

# force Nvidia
export LIBVA_DRIVER_NAME=nvidia

# run
exec /opt/google/chrome/google-chrome "${flags[@]}" "$@"
