#!/usr/bin/env bash


# Debug
# - chrome://gpu 
# - F12 devtools, 'Media' tab
# Reference docs:
# - https://wiki.archlinux.org/title/Chromium
# - https://wiki.archlinux.org/title/Hardware_video_acceleration

# define chrome launch flags
flags=(
    # wallet integration
    --password-store=kwallet6

    # force Nvidia
    --enable-features=VaapiOnNvidiaGPUs
)

# force Nvidia
export LIBVA_DRIVER_NAME=nvidia

# run
exec /opt/google/chrome/google-chrome "${flags[@]}" "$@"
