#!/bin/sh

stow_dir="$(dirname "$(realpath "$0")")/_"
target_dir="$HOME/.local/share/Steam/steamapps/compatdata/227300/pfx/drive_c/users/steamuser/Documents/Euro Truck Simulator 2"


. $XDG_CONFIG_HOME/workspace/stow "$stow_dir" "$target_dir" "$@"
