[preferred]
# screen sharing
org.freedesktop.impl.portal.ScreenCast=gnome;gtk;
org.freedesktop.impl.portal.Screenshot=gnome;gtk;

# File chooser
org.freedesktop.impl.portal.FileChooser=kde;

# Fallback
default=kde;gnome;*
