#!/bin/sh

stow_dir="$(dirname "$(realpath "$0")")/_"
target_dir="$(echo "$HOME/.local/share/Steam/steamapps/compatdata/270880/pfx/drive_c/users/steamuser/Documents/American Truck Simulator/steam_profiles/"*)"


. $XDG_CONFIG_HOME/workspace/stow "$stow_dir" "$target_dir" "$@"
