# force Windows games to run natively on the Wayland display protocol through Proton
# BUG: 
# enable this globally will break some legacy app, e.g. ubisoft connect
# division 2 also runs with very poor performance with weird display font
# PROTON_ENABLE_WAYLAND=1
