# Background & Primary Text
background=#111
foreground=#fff
cursor=#fff

# Black / Grey
color0=#444
color8=#888

# Red
color1=#d36
color9=#f58

# Green
color2=#3d7
color10=#5f9

# Yellow
color3=#dd8
color11=#ff8

# Blue
color4=#08d
color12=#2af

# Magenta / Purple
color5=#b6d
color13=#d8f

# Cyan
color6=#4dd
color14=#6ff

# White
color7=#eee
color15=#fff

# vim: ft=bash
