# Background & Primary Text
background=#000
foreground=#fff
cursor=#fff

# Black / Grey
color0=#444
color8=#888

# Red
color1=#d88
color9=#faa

# Green
color2=#8d8
color10=#afa

# Yellow
color3=#dd8
color11=#ff8

# Blue
color4=#08d
color12=#2af

# Magenta / Purple
color5=#b6d
color13=#d8f

# Cyan
color6=#8dd
color14=#aff

# White
color7=#eee
color15=#fff

# vim: ft=bash
