#!/bin/sh

stow_dir="$(dirname "$(realpath "$0")")/_"
target_dir="$HOME/.local/share/Steam/steamapps/compatdata/244210/pfx/drive_c/users/steamuser/AppData/Local/AcTools Content Manager/Presets"

. $XDG_CONFIG_HOME/workspace/stow "$stow_dir" "$target_dir" "$@"
